// DEMO DATA — swap for API call when real data is available

export interface DemoRentalCar {
  id: string;
  title: string;
  make: string;
  model: string;
  year: number;
  type: string;
  pricePerDay: number;
  district: string;
  province: string;
  seats: number;
  transmission: 'Auto' | 'Manual';
  drivingOption: 'Self-Drive' | 'With Driver' | 'Both';
  listingType: 'P2P' | 'Fleet';
  rating: number;
  reviewCount: number;
  images: string[];
  hostName: string;
  hostAvatar: string;
  hostVerified: boolean;
  hostMemberSince: string;
  hostResponseRate: string;
  available: boolean;
  features: string[];
  description: string;
  fuel: string;
}

export interface DemoTestimonial {
  name: string;
  role: string;
  avatar: string | null;
  text: string;
  rating: number;
}

export const DEMO_STATS = [
  { label: 'Verified Cars', value: '30+' },
  { label: 'Trips Completed', value: '500+' },
  { label: 'Districts Covered', value: '30' },
  { label: 'Avg. Rating', value: '4.8★' },
];

export const DEMO_RENTAL_CARS: DemoRentalCar[] = [
  {
    id: 'demo-001',
    title: 'Toyota Vitz 2018 — Self Drive',
    make: 'Toyota', model: 'Vitz', year: 2018, type: 'Economy',
    pricePerDay: 28000, district: 'gasabo', province: 'Kigali City',
    seats: 5, transmission: 'Auto', drivingOption: 'Self-Drive', listingType: 'P2P',
    rating: 4.7, reviewCount: 23,
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800', 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800'],
    hostName: 'Amahoro Jean', hostAvatar: 'https://i.pravatar.cc/60?img=11', hostVerified: true,
    hostMemberSince: 'March 2025', hostResponseRate: '97%', available: true,
    features: ['Air Conditioning', 'USB Charging', 'Bluetooth Audio', 'Spare Tyre'],
    description: 'Well-maintained Toyota Vitz perfect for city driving in Kigali. Full tank provided, return with same level.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-002',
    title: 'Toyota Fielder 2019 — Self Drive',
    make: 'Toyota', model: 'Fielder', year: 2019, type: 'Economy',
    pricePerDay: 32000, district: 'kicukiro', province: 'Kigali City',
    seats: 5, transmission: 'Auto', drivingOption: 'Self-Drive', listingType: 'P2P',
    rating: 4.8, reviewCount: 41,
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800', 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800'],
    hostName: 'Uwimana Grace', hostAvatar: 'https://i.pravatar.cc/60?img=22', hostVerified: true,
    hostMemberSince: 'January 2025', hostResponseRate: '100%', available: true,
    features: ['Air Conditioning', 'GPS Navigation', 'USB Charging', 'Child Seat Available'],
    description: 'Spacious Toyota Fielder station wagon, ideal for families or groups up to 5. Available for self-drive across Rwanda.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-003',
    title: 'Toyota Corolla 2020 — Self Drive',
    make: 'Toyota', model: 'Corolla', year: 2020, type: 'Sedan',
    pricePerDay: 48000, district: 'nyarugenge', province: 'Kigali City',
    seats: 5, transmission: 'Auto', drivingOption: 'Both', listingType: 'Fleet',
    rating: 4.9, reviewCount: 67,
    images: ['https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800', 'https://images.unsplash.com/photo-1561020469-fb4e2e20bf52?w=800'],
    hostName: 'Kigali Fleet Services', hostAvatar: 'https://i.pravatar.cc/60?img=33', hostVerified: true,
    hostMemberSince: 'October 2024', hostResponseRate: '99%', available: true,
    features: ['Air Conditioning', 'GPS Navigation', 'Dash Cam', 'USB Charging', 'Insurance Included'],
    description: 'Latest model Toyota Corolla from our certified fleet. Available self-drive or with professional driver for business trips.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-004',
    title: 'Toyota Premio 2019 — With Driver',
    make: 'Toyota', model: 'Premio', year: 2019, type: 'Sedan',
    pricePerDay: 52000, district: 'gasabo', province: 'Kigali City',
    seats: 5, transmission: 'Auto', drivingOption: 'With Driver', listingType: 'P2P',
    rating: 4.6, reviewCount: 19,
    images: ['https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800', 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800'],
    hostName: 'Bizimana Patrick', hostAvatar: 'https://i.pravatar.cc/60?img=44', hostVerified: true,
    hostMemberSince: 'February 2025', hostResponseRate: '94%', available: true,
    features: ['Air Conditioning', 'Professional Driver', 'Airport Pickup', 'Bluetooth Audio'],
    description: 'Comfortable Toyota Premio with experienced English-speaking driver. Ideal for airport transfers and business meetings.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-005',
    title: 'Toyota RAV4 2021 — Self Drive',
    make: 'Toyota', model: 'RAV4', year: 2021, type: 'SUV / 4x4',
    pricePerDay: 75000, district: 'gasabo', province: 'Kigali City',
    seats: 5, transmission: 'Auto', drivingOption: 'Self-Drive', listingType: 'P2P',
    rating: 5.0, reviewCount: 34,
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800', 'https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800'],
    hostName: 'Nkurunziza David', hostAvatar: 'https://i.pravatar.cc/60?img=55', hostVerified: true,
    hostMemberSince: 'December 2024', hostResponseRate: '98%', available: true,
    features: ['Air Conditioning', 'GPS Navigation', '4WD', 'USB Charging', 'Roof Rack', 'First Aid Kit'],
    description: 'Top-rated RAV4 perfect for gorilla trekking in Musanze or safari in Akagera. Full insurance and roadside assistance included.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-006',
    title: 'Suzuki Vitara 2020 — Self Drive',
    make: 'Suzuki', model: 'Vitara', year: 2020, type: 'SUV / 4x4',
    pricePerDay: 65000, district: 'kicukiro', province: 'Kigali City',
    seats: 5, transmission: 'Auto', drivingOption: 'Both', listingType: 'P2P',
    rating: 4.7, reviewCount: 28,
    images: ['https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800', 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800'],
    hostName: 'Mukamusoni Aline', hostAvatar: 'https://i.pravatar.cc/60?img=48', hostVerified: false,
    hostMemberSince: 'April 2025', hostResponseRate: '91%', available: true,
    features: ['Air Conditioning', '4WD', 'USB Charging', 'Bluetooth Audio'],
    description: 'Compact SUV great for exploring Rwanda highlands. Easy to drive on both tarmac and murram roads.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-007',
    title: 'Toyota Land Cruiser Prado — With Driver',
    make: 'Toyota', model: 'Land Cruiser Prado', year: 2020, type: 'SUV / 4x4',
    pricePerDay: 140000, district: 'musanze', province: 'Northern Province',
    seats: 7, transmission: 'Auto', drivingOption: 'With Driver', listingType: 'Fleet',
    rating: 5.0, reviewCount: 52,
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800', 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800'],
    hostName: 'Volcanoes Safari Fleet', hostAvatar: 'https://i.pravatar.cc/60?img=15', hostVerified: true,
    hostMemberSince: 'September 2024', hostResponseRate: '100%', available: true,
    features: ['Air Conditioning', 'GPS Navigation', '4WD Low-Range', 'Professional Driver', 'Cooler Box', 'First Aid Kit', 'Recovery Kit'],
    description: 'Premium Prado for gorilla trekking at Volcanoes National Park. Includes certified safari driver and all permits assistance.',
    fuel: 'Diesel',
  },
  {
    id: 'demo-008',
    title: 'Toyota Land Cruiser V8 — With Driver',
    make: 'Toyota', model: 'Land Cruiser V8', year: 2021, type: 'Luxury',
    pricePerDay: 320000, district: 'nyarugenge', province: 'Kigali City',
    seats: 8, transmission: 'Auto', drivingOption: 'With Driver', listingType: 'Fleet',
    rating: 5.0, reviewCount: 18,
    images: ['https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800', 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800'],
    hostName: 'Executive Rwanda Transport', hostAvatar: 'https://i.pravatar.cc/60?img=60', hostVerified: true,
    hostMemberSince: 'July 2024', hostResponseRate: '100%', available: true,
    features: ['Air Conditioning', 'GPS Navigation', 'Leather Seats', 'Professional Chauffeur', 'Mineral Water', 'WiFi Hotspot', 'Tinted Windows'],
    description: 'VIP Land Cruiser V8 for dignitaries and executive travel. Fully insured with licensed professional chauffeur.',
    fuel: 'Diesel',
  },
  {
    id: 'demo-009',
    title: 'Toyota Hiace 14-Seater — With Driver',
    make: 'Toyota', model: 'Hiace 14-Seater', year: 2020, type: 'Minibus',
    pricePerDay: 110000, district: 'gasabo', province: 'Kigali City',
    seats: 14, transmission: 'Manual', drivingOption: 'With Driver', listingType: 'Fleet',
    rating: 4.8, reviewCount: 45,
    images: ['https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800', 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800'],
    hostName: 'Kigali Group Transport', hostAvatar: 'https://i.pravatar.cc/60?img=30', hostVerified: true,
    hostMemberSince: 'November 2024', hostResponseRate: '96%', available: true,
    features: ['Air Conditioning', 'Professional Driver', 'Luggage Rack', 'USB Charging', 'First Aid Kit'],
    description: 'Spacious Hiace minibus perfect for group tours, weddings, and corporate transfers across Rwanda.',
    fuel: 'Diesel',
  },
  {
    id: 'demo-010',
    title: 'Toyota Coaster 30-Seater — With Driver',
    make: 'Toyota', model: 'Coaster Bus', year: 2021, type: 'Minibus',
    pricePerDay: 280000, district: 'nyarugenge', province: 'Kigali City',
    seats: 30, transmission: 'Manual', drivingOption: 'With Driver', listingType: 'Fleet',
    rating: 4.9, reviewCount: 22,
    images: ['https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800', 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800'],
    hostName: 'Kigali Group Transport', hostAvatar: 'https://i.pravatar.cc/60?img=30', hostVerified: true,
    hostMemberSince: 'November 2024', hostResponseRate: '96%', available: true,
    features: ['Air Conditioning', 'Professional Driver', 'Reclining Seats', 'Luggage Bay', 'PA System'],
    description: 'Full-size coach for large groups and conference transfers. Air-conditioned with experienced driver and guide.',
    fuel: 'Diesel',
  },
  {
    id: 'demo-011',
    title: 'Toyota Hilux 2020 — Self Drive',
    make: 'Toyota', model: 'Hilux', year: 2020, type: 'Pickup',
    pricePerDay: 90000, district: 'rubavu', province: 'Western Province',
    seats: 5, transmission: 'Manual', drivingOption: 'Self-Drive', listingType: 'P2P',
    rating: 4.6, reviewCount: 17,
    images: ['https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800', 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800'],
    hostName: 'Habimana Eric', hostAvatar: 'https://i.pravatar.cc/60?img=20', hostVerified: true,
    hostMemberSince: 'January 2025', hostResponseRate: '89%', available: true,
    features: ['Air Conditioning', '4WD', 'Tow Bar', 'Cargo Bed Liner'],
    description: 'Heavy-duty Hilux pickup for Lake Kivu tours or construction site work around Rubavu. Handles all terrain.',
    fuel: 'Diesel',
  },
  {
    id: 'demo-012',
    title: 'Mercedes-Benz E-Class — Chauffeur',
    make: 'Mercedes-Benz', model: 'E-Class', year: 2022, type: 'Executive',
    pricePerDay: 220000, district: 'nyarugenge', province: 'Kigali City',
    seats: 5, transmission: 'Auto', drivingOption: 'With Driver', listingType: 'Fleet',
    rating: 5.0, reviewCount: 31,
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800', 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800'],
    hostName: 'Premium Kigali Rides', hostAvatar: 'https://i.pravatar.cc/60?img=65', hostVerified: true,
    hostMemberSince: 'August 2024', hostResponseRate: '100%', available: true,
    features: ['Air Conditioning', 'Leather Seats', 'Professional Chauffeur', 'Mineral Water', 'WiFi', 'Meet & Greet Service'],
    description: 'Luxury Mercedes E-Class for airport VIP arrivals, Kigali Convention Centre transfers, and diplomatic missions.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-013',
    title: 'BMW 5 Series — Chauffeur',
    make: 'BMW', model: '5 Series', year: 2022, type: 'Executive',
    pricePerDay: 250000, district: 'gasabo', province: 'Kigali City',
    seats: 5, transmission: 'Auto', drivingOption: 'With Driver', listingType: 'Fleet',
    rating: 5.0, reviewCount: 14,
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800'],
    hostName: 'Premium Kigali Rides', hostAvatar: 'https://i.pravatar.cc/60?img=65', hostVerified: true,
    hostMemberSince: 'August 2024', hostResponseRate: '100%', available: true,
    features: ['Air Conditioning', 'Leather Seats', 'Professional Chauffeur', 'Mineral Water', 'WiFi Hotspot', 'Privacy Glass'],
    description: 'Business-class BMW 5 Series for executive meetings and state functions. Punctual, discreet, professional.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-014',
    title: 'Range Rover Sport — Luxury',
    make: 'Land Rover', model: 'Range Rover Sport', year: 2021, type: 'Luxury',
    pricePerDay: 380000, district: 'nyarugenge', province: 'Kigali City',
    seats: 5, transmission: 'Auto', drivingOption: 'Both', listingType: 'Fleet',
    rating: 5.0, reviewCount: 9,
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800', 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800'],
    hostName: 'Executive Rwanda Transport', hostAvatar: 'https://i.pravatar.cc/60?img=60', hostVerified: true,
    hostMemberSince: 'July 2024', hostResponseRate: '100%', available: true,
    features: ['Air Conditioning', 'Panoramic Roof', 'Premium Sound', 'Professional Chauffeur', 'Full-Size Spare', '360° Cameras'],
    description: 'The ultimate luxury SUV for high-profile visits, weddings, and mountain drives. Self-drive or chauffeured.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-015',
    title: 'Toyota RAV4 2019 — With Driver',
    make: 'Toyota', model: 'RAV4', year: 2019, type: 'SUV / 4x4',
    pricePerDay: 85000, district: 'huye', province: 'Southern Province',
    seats: 5, transmission: 'Auto', drivingOption: 'With Driver', listingType: 'P2P',
    rating: 4.8, reviewCount: 29,
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800', 'https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800'],
    hostName: 'Ingabire Solange', hostAvatar: 'https://i.pravatar.cc/60?img=49', hostVerified: true,
    hostMemberSince: 'February 2025', hostResponseRate: '95%', available: true,
    features: ['Air Conditioning', 'GPS', 'Professional Driver', '4WD', 'Child Seat', 'USB Charging'],
    description: 'Perfect for exploring the Southern Province — from University of Rwanda in Huye to Nyungwe Forest. Driver speaks English and French.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-016',
    title: 'Toyota Land Cruiser Prado — Self Drive',
    make: 'Toyota', model: 'Land Cruiser Prado', year: 2018, type: 'SUV / 4x4',
    pricePerDay: 125000, district: 'nyagatare', province: 'Eastern Province',
    seats: 7, transmission: 'Auto', drivingOption: 'Self-Drive', listingType: 'P2P',
    rating: 4.9, reviewCount: 38,
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800', 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800'],
    hostName: 'Mutabazi Jean-Baptiste', hostAvatar: 'https://i.pravatar.cc/60?img=8', hostVerified: true,
    hostMemberSince: 'November 2024', hostResponseRate: '97%', available: true,
    features: ['Air Conditioning', 'GPS Navigation', '4WD Low-Range', 'Roof Rack', 'Recovery Kit', 'Fridge'],
    description: 'Robust Prado for Akagera National Park safaris. Drop-off available at Rwamagana gate. Full insurance included.',
    fuel: 'Diesel',
  },
  {
    id: 'demo-017',
    title: 'Toyota Vitz 2020 — Self Drive',
    make: 'Toyota', model: 'Vitz', year: 2020, type: 'Economy',
    pricePerDay: 30000, district: 'rwamagana', province: 'Eastern Province',
    seats: 5, transmission: 'Auto', drivingOption: 'Self-Drive', listingType: 'P2P',
    rating: 4.5, reviewCount: 12,
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800', 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800'],
    hostName: 'Nzabonimpa Thierry', hostAvatar: 'https://i.pravatar.cc/60?img=40', hostVerified: false,
    hostMemberSince: 'March 2025', hostResponseRate: '88%', available: true,
    features: ['Air Conditioning', 'USB Charging', 'Spare Tyre'],
    description: 'Reliable city car for Rwamagana district. Easy parking, low fuel consumption, perfect for short trips.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-018',
    title: 'Toyota Hilux 2021 — With Driver',
    make: 'Toyota', model: 'Hilux', year: 2021, type: 'Pickup',
    pricePerDay: 100000, district: 'rusizi', province: 'Western Province',
    seats: 5, transmission: 'Manual', drivingOption: 'With Driver', listingType: 'Fleet',
    rating: 4.7, reviewCount: 21,
    images: ['https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800', 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800'],
    hostName: 'Kivu Transport Solutions', hostAvatar: 'https://i.pravatar.cc/60?img=25', hostVerified: true,
    hostMemberSince: 'December 2024', hostResponseRate: '93%', available: true,
    features: ['Air Conditioning', 'Professional Driver', '4WD', 'Cargo Bed', 'Tow Bar'],
    description: 'Hilux pickup with driver for DRC border runs, Cyangugu market trips, and Lake Kivu tours.',
    fuel: 'Diesel',
  },
  {
    id: 'demo-019',
    title: 'Toyota Corolla 2019 — Self Drive',
    make: 'Toyota', model: 'Corolla', year: 2019, type: 'Sedan',
    pricePerDay: 42000, district: 'karongi', province: 'Western Province',
    seats: 5, transmission: 'Auto', drivingOption: 'Self-Drive', listingType: 'P2P',
    rating: 4.6, reviewCount: 16,
    images: ['https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800', 'https://images.unsplash.com/photo-1561020469-fb4e2e20bf52?w=800'],
    hostName: 'Uwase Clarisse', hostAvatar: 'https://i.pravatar.cc/60?img=47', hostVerified: true,
    hostMemberSince: 'January 2025', hostResponseRate: '96%', available: true,
    features: ['Air Conditioning', 'GPS Navigation', 'Bluetooth Audio', 'USB Charging'],
    description: 'Clean Corolla available for Lake Kivu road trips from Karongi. Scenic drives to Gisenyi included in tour packages.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-020',
    title: 'Toyota RAV4 2022 — Self Drive',
    make: 'Toyota', model: 'RAV4', year: 2022, type: 'SUV / 4x4',
    pricePerDay: 88000, district: 'musanze', province: 'Northern Province',
    seats: 5, transmission: 'Auto', drivingOption: 'Both', listingType: 'P2P',
    rating: 4.9, reviewCount: 33,
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800', 'https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800'],
    hostName: 'Nsanzimana Didier', hostAvatar: 'https://i.pravatar.cc/60?img=35', hostVerified: true,
    hostMemberSince: 'October 2024', hostResponseRate: '99%', available: true,
    features: ['Air Conditioning', 'GPS Navigation', '4WD', 'USB Charging', 'Parking Sensors', 'Backup Camera'],
    description: 'Latest RAV4 based in Musanze, minutes from Volcanoes National Park. Available with or without driver for gorilla treks.',
    fuel: 'Petrol',
  },
  {
    id: 'demo-021',
    title: 'Isuzu FSR Truck — With Driver',
    make: 'Isuzu', model: 'FSR Truck', year: 2019, type: 'Pickup',
    pricePerDay: 180000, district: 'kicukiro', province: 'Kigali City',
    seats: 3, transmission: 'Manual', drivingOption: 'With Driver', listingType: 'Fleet',
    rating: 4.8, reviewCount: 37,
    images: ['https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800', 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800'],
    hostName: 'Rwanda Heavy Logistics', hostAvatar: 'https://i.pravatar.cc/60?img=18', hostVerified: true,
    hostMemberSince: 'August 2024', hostResponseRate: '98%', available: true,
    features: ['Air Conditioning', 'Professional Driver', 'Flatbed Cargo', '5-Ton Capacity', 'GPS Tracking'],
    description: 'Heavy-duty truck with professional driver for cargo transport. Covers all Rwanda districts with proper loading/unloading.',
    fuel: 'Diesel',
  },
  {
    id: 'demo-022',
    title: 'Nissan X-Trail 2020 — Self Drive',
    make: 'Nissan', model: 'X-Trail', year: 2020, type: 'SUV / 4x4',
    pricePerDay: 72000, district: 'rubavu', province: 'Western Province',
    seats: 5, transmission: 'Auto', drivingOption: 'Self-Drive', listingType: 'P2P',
    rating: 4.5, reviewCount: 15,
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800', 'https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800'],
    hostName: 'Murenzi Pascal', hostAvatar: 'https://i.pravatar.cc/60?img=42', hostVerified: false,
    hostMemberSince: 'April 2025', hostResponseRate: '87%', available: true,
    features: ['Air Conditioning', '4WD', 'USB Charging', 'Bluetooth Audio', 'Roof Rack'],
    description: 'Reliable X-Trail for Gisenyi beach trips and Congo Nile Trail cycling support. Comfortable for 5 passengers plus luggage.',
    fuel: 'Petrol',
  },
];

export const DEMO_TESTIMONIALS: DemoTestimonial[] = [
  {
    name: 'Jean-Pierre Habimana',
    role: 'Host — Gasabo, Kigali',
    avatar: null,
    text: 'I listed my Toyota RAV4 on Gari and earned over RWF 800,000 in my first month. The platform handles bookings, payments, and even insurance. I just hand over the keys.',
    rating: 5,
  },
  {
    name: 'Amina Kalisa',
    role: 'Renter — Musanze',
    avatar: null,
    text: 'Found a beautiful Prado 4x4 for our Volcanoes National Park gorilla trekking trip in minutes. MTN MoMo payment was instant. Best car rental experience in Rwanda.',
    rating: 5,
  },
  {
    name: 'David Nkurunziza',
    role: 'Fleet Owner — Rubavu',
    avatar: null,
    text: 'As a fleet operator in Rubavu, Gari gave us a digital presence overnight. Our Hiace minibuses are now booked weeks in advance for Lake Kivu tours.',
    rating: 5,
  },
  {
    name: 'Immaculée Uwimana',
    role: 'Renter — Nyarugenge',
    avatar: null,
    text: 'Used Gari for the Kigali Convention Centre Summit transfers. The Mercedes was immaculate and the chauffeur was punctual and professional. Highly recommended.',
    rating: 5,
  },
  {
    name: 'Eric Murenzi',
    role: 'Host — Huye',
    avatar: null,
    text: 'Listed my Corolla on Gari to cover loan repayments. It now earns enough to pay itself off while I use it on weekends. Smart platform for Rwandan car owners.',
    rating: 4,
  },
  {
    name: 'Clarisse Uwase',
    role: 'Renter — Karongi',
    avatar: 'https://i.pravatar.cc/60?img=44',
    text: 'Perfect for our family road trip around Lake Kivu. The self-drive RAV4 was clean, fully fuelled, and the host met us at Karongi ferry terminal.',
    rating: 5,
  },
];

// Earnings calculator daily rates by car type
export const EARNINGS_RATES: Record<string, number> = {
  'Economy': 30000,
  'Sedan': 47000,
  'SUV / 4x4': 77000,
  'Executive': 215000,
  'Minibus': 120000,
  'Pickup': 95000,
  'Luxury': 375000,
};
